feat(package/weather): Version 1.0 of weather package
leon-ai/leon pull request #108
Opened 2019-06-09 09:44 UTC by Imperator26

### What type of change does this PR introduce?
- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Documentation
- [ ] Not Sure?

### Does this PR introduce breaking changes?
- [ ] Yes
- [x] No

### List any relevant issue numbers:
[#105](https://github.com/leon-ai/leon/issues/105#issuecomment-500193278)

### Description:
New weather package.

2019-06-09 10:25 UTC, louistiti commented
Hello @Imperator26,

Thanks for opening this PR and for that work!

I'll take a look at it later. Let's see how we can deal with both of these packages https://github.com/leon-ai/leon/pull/103.

Also, today I've created a Discord so that we can discuss further, feel free to [join it](https://discord.gg/MNQqqKg).

2021-03-23 07:41 UTC, Divlo commented on bridges/python/Pipfile
> +pyowm = "==2.10.0"
This PR is quite old, before we merge, we should use the latest versions of the dependencies used in this package.
Currently the latest version of `pyowm` is `3.2.0` and `tzlocal` is `2.1`.

2021-03-23 08:25 UTC, Divlo requested changes
Thanks for your contribution! @facorazza 

I submit several comments about your code, feel free to discuss.
Also there isn't automated tests for this package, we should add some.

2021-03-23 08:25 UTC, Divlo commented on packages/weather/OpenWeatherMap.py
> +    dt = payload["wtr"].get_sunrise_time("date")
We should avoid abbreviations in variable names.
So instead to call it `dt`, we could call it `date_time` for example.

2025-11-25 21:42 UTC, closed without merging